#!/usr/local/bin/php
<?php
/**
 * This example demonstrates how to notify via Email and Slack
 * using the ENV parameters (from the .env file)
 */
declare(strict_types=1);

require dirname(__DIR__) . '/../vendor/autoload.php';

use Chemaclass\JiraStatusNotifier\Channel\Cli;
use Chemaclass\JiraStatusNotifier\Channel\Email;
use Chemaclass\JiraStatusNotifier\Channel\Email\ByPassEmail;
use Chemaclass\JiraStatusNotifier\Channel\MessageGenerator;
use Chemaclass\JiraStatusNotifier\Channel\Slack;
use Chemaclass\JiraStatusNotifier\Common\EnvKeys;
use Chemaclass\JiraStatusNotifier\IO\EchoOutput;
use Chemaclass\JiraStatusNotifier\IO\JiraConnectorInput;
use Chemaclass\JiraStatusNotifier\IO\NotifierOutput;
use Chemaclass\JiraStatusNotifier\Jira\JiraHttpClient;
use Chemaclass\JiraStatusNotifier\Jira\JiraTicketsFactory;
use Chemaclass\JiraStatusNotifier\JiraConnector;
use Dotenv\Dotenv;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\Mailer\Bridge\Google\Transport\GmailSmtpTransport;
use Symfony\Component\Mailer\Mailer;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

Dotenv::create(__DIR__)->load();
EnvKeys::create((array)getenv())->validate(file_get_contents(__DIR__ . '/.env.dist'));

$twig = new Environment(new FilesystemLoader('../templates'));

$jiraHttpClient = new JiraHttpClient(
    HttpClient::create([
        'auth_basic' => [getenv('JIRA_API_LABEL'), getenv('JIRA_API_PASSWORD')],
    ]),
    new JiraTicketsFactory(['customfield_10005' => 'StoryPoints'])
);

$channels = [
    new Email\Channel(
        new Mailer(new GmailSmtpTransport(getenv('MAILER_USERNAME'), getenv('MAILER_PASSWORD'))),
        new MessageGenerator(new DateTimeImmutable(), $twig, 'email-template.twig'),
        new Email\AddressGenerator((new ByPassEmail())
            ->setSendEmailsToAssignee(false) // <- OverriddenEmails wont have no effect as long as this is false
            ->setOverriddenEmails(json_decode(getenv('OVERRIDDEN_EMAILS'), true))
            ->setSendCopyTo(getenv('MAILER_USERNAME')))
    ),
    new Slack\Channel(
        new Slack\HttpClient(HttpClient::create([
            'auth_bearer' => getenv('SLACK_BOT_USER_OAUTH_ACCESS_TOKEN'),
        ])),
        Slack\JiraMapping::jiraNameWithSlackId(json_decode(getenv('SLACK_MAPPING_IDS'), true)),
        new MessageGenerator(new DateTimeImmutable(), $twig, 'slack-template.twig')
    ),
    new Cli\Channel(),
];

$jiraConnector = new JiraConnector($jiraHttpClient, ...$channels);

$result = $jiraConnector->handle(JiraConnectorInput::new(
    getenv(JiraConnectorInput::COMPANY_NAME),
    getenv(JiraConnectorInput::JIRA_PROJECT_NAME),
    json_decode(getenv(JiraConnectorInput::DAYS_FOR_STATUS), true),
    json_decode(getenv(JiraConnectorInput::JIRA_USERS_TO_IGNORE), true)
));

(new NotifierOutput(new EchoOutput(), $twig))
    ->write($result, 'output/channel-result.twig');
