#!/usr/local/bin/php
<?php
/**
 * This example demonstrates how to notify via the client terminal
 * using the ENV parameters (from the .env file)
 */
declare(strict_types=1);

require dirname(__DIR__) . '/../vendor/autoload.php';

use Chemaclass\JiraStatusNotifier\Domain\Channel\Cli\CliChannel;
use Chemaclass\JiraStatusNotifier\Domain\Common\EnvKeys;
use Chemaclass\JiraStatusNotifier\JiraStatusNotifierFacade;
use Dotenv\Dotenv;
use Gacela\Framework\Gacela;

Dotenv::create(__DIR__)->load();
EnvKeys::create((array)getenv())->validate(file_get_contents(__DIR__ . '/.env.dist'));

Gacela::bootstrap(__DIR__, [
    'config' => [
        'type' => 'env',
        'path' => '.env',
    ],
]);

$facade = new JiraStatusNotifierFacade();
$result = $facade->handle([
    CliChannel::class,
]);

$facade->renderOutput($result);
