language: php
cache: false
sudo: false

php:
  - 7.4

before_install:
  - composer install

script:
  - ./vendor/bin/phpunit tests --coverage-clover tests/clover.xml --configuration phpunit.xml --coverage-clover tests/clover.xml
  - ./vendor/bin/php-cs-fixer
  - ./vendor/bin/infection --min-msi=86 --min-covered-msi=86
